# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.create(username: "John", password: "password", location: "New York City", age: 25)
User.create(username: "Jane", password: "password", location: "Boston")
User.create(username: "Adam", password: "password", location: "San Francisco", age: 11)
User.create(username: "Alicia", password: "password", location: "Houston", age: 72)
User.create(username: "Wendy", password: "password", location: "Chicago")
User.create(username: "Admin", password: "StorySwap", location: "StorySwap", admin: true, age: 100)

Question.create(title: "What was the last great meal you had?", description: "Lunch, dinner, supper, breakfast, let's hear about them all!")
Question.create(title: "What inspires you?")
Question.create(title: "Who is the most important person in your life?", description: "Grandmas, uncles, pets, teachers, the list could go on!")
Question.create(title: "What are you grateful for?")
Question.create(title: "What do you think about when you can't fall asleep?")
Question.create(title: "What experiences made you who you are today?")
Question.create(title: "What made you smile this week?")

Answer.create(question_id: 1, user_id: 1, username: "John", user_location: "New York City", body: "I had an amazing lunch in Paris once, we were on the Seine and eating croissants and I felt like the perfect tourist.", user_age: 25)
Answer.create(question_id: 1, user_id: 2, username: "Jane", user_location: "Boston", body: "I had an amazing time drinking horse milk in a yurt in Inner Mongolia. It was peaceful and serene and it didn't taste half bad either.")
Answer.create(question_id: 2, user_id: 2, username: "Jane", user_location: "Boston", body: "Definitely my passion for painting comes from the classes I took in high school. I knew I wasn't good but that if I worked at it I could make something I loved and that has kept me going")
Answer.create(question_id: 1, user_id: 3, username: "Adam", user_location: "San Francisco", body: "The bakeries in San Francisco are near and dear to my heart. I think that it's about the soul of the sourdough. Mmmm. Yeast.", user_age: 11)
Answer.create(question_id: 2, user_id: 3, username: "Adam", user_location: "San Francisco", body: "The rain inspires me. I think the serenity is something I plan to hold inside me and feeling the natural world is something that's always been a part of me", user_age: 11)
Answer.create(question_id: 1, username: "Guest", user_location: "Sydney, Australia", user_age: 14, body: "I ate a steak off the floor the other day when I was so tired I dropped it but thought it was easier to just eat it off the floor than pick it up again. It was really earthy and interesting.")
Answer.create(question_id: 3, username: "Guest", user_location: "Los Angeles", body: "The most important person to me is my mom because she raised me and helped me become the best person I can be. I remember one day she gave me my favorite cereal and it made me strong.")

Comment.create(answer_id: 1, user_id: 2, username: "Jane", user_location: "Boston", body: "That's amazing! I went there and ate a baguette while on the Eiffel Tower! Hahaha!")
Comment.create(answer_id: 1, username: "Guest", user_age: 14, user_location: "Sydney, Australia", body: "LOL! Croissants all the way!!")
Comment.create(answer_id: 1, username: "Guest", user_location: "Los Angeles", body: "I love France. So romantic")
Comment.create(answer_id: 7, username: "Guest", user_age: 14, user_location: "Sydney, Australia", body: "I love cereal, but I buy it myself because my parents always get it mixed up.")

Vote.create(user_id: 2, votable_type: "Answer", votable_id: 1, value: 1)
Vote.create(user_id: 1, votable_type: "Answer", votable_id: 1, value: 1)
Vote.create(user_id: 3, votable_type: "Answer", votable_id: 1, value: 1)
Vote.create(user_id: 4, votable_type: "Answer", votable_id: 1, value: 1)
Vote.create(user_id: 5, votable_type: "Answer", votable_id: 1, value: 1)
Vote.create(user_id: 1, votable_type: "Answer", votable_id: 2, value: 1)
Vote.create(user_id: 2, votable_type: "Answer", votable_id: 2, value: 1)
Vote.create(user_id: 3, votable_type: "Answer", votable_id: 2, value: 1)
Vote.create(user_id: 1, votable_type: "Answer", votable_id: 3, value: 1)
Vote.create(user_id: 1, votable_type: "Answer", votable_id: 4, value: 1)
Vote.create(user_id: 1, votable_type: "Answer", votable_id: 5, value: 1)
Vote.create(user_id: 1, votable_type: "Comment", votable_id: 1, value: 1)
Vote.create(user_id: 1, votable_type: "Comment", votable_id: 2, value: 1)
Vote.create(user_id: 1, votable_type: "Comment", votable_id: 3, value: 1)
Vote.create(user_id: 1, votable_type: "Comment", votable_id: 4, value: 1)
Vote.create(user_id: 2, votable_type: "Comment", votable_id: 1, value: 1)
Vote.create(user_id: 3, votable_type: "Comment", votable_id: 2, value: 1)
Vote.create(user_id: 4, votable_type: "Comment", votable_id: 3, value: 1)
Vote.create(user_id: 5, votable_type: "Comment", votable_id: 4, value: 1)
Vote.create(user_id: 2, votable_type: "Comment", votable_id: 4, value: 1)
Vote.create(user_id: 3, votable_type: "Comment", votable_id: 4, value: 1)
Vote.create(user_id: 4, votable_type: "Comment", votable_id: 4, value: 1)
Vote.create(user_id: 5, votable_type: "Comment", votable_id: 2, value: 1)
Vote.create(user_id: 5, votable_type: "Comment", votable_id: 3, value: 1)
